apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-restaurant-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-restaurant-order
  template:
    metadata:
      labels:
        app: dog-restaurant-order
    spec:
      hostname: dog-restaurant-order
      serviceAccountName: dog-service-account
      containers:
      - name: dog-restaurant-order
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/dog-restaurant-order:latest
        resources:
          requests:
            cpu: 100m
            memory: "1024Mi"
          limits:
            cpu: 1000m
            memory: "2048Mi"
        ports:
        - containerPort: 3000
        env:
        - name: CLIENTES_API_URL
          value: ''
        - name: PRODUTOS_API_URL
          value: ''  
        - name: PAGAMENTOS_API_URL
          value: 'http://dog-restaurant-payments.default.svc.cluster.local:80'                  
        - name: AWS_REGION
          value: "us-east-1"   
        - name: DB_NAME
          value: "DB_NAME_PLACEHOLDER"
        - name: DB_PORT
          value: "DB_PORT_PLACEHOLDER"    
        - name: DB_USER
          value: "DB_USER_PLACEHOLDER"     
        - name: DB_PASSWORD
          value: "DB_PASSWORD_PLACEHOLDER"
        - name: DB_HOST
          value: "DB_HOST_PLACEHOLDER"