apiVersion: v1
kind: Service
metadata:
  name: dog-restaurant-order-lb
  namespace: default
spec:
  selector:
    app: dog-restaurant-order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer